POST https://www.youtube.com/youtubei/v1/get_transcript?prettyPrint=false
content-Type: application/json;

{
    "context": {
        "client": {
            "clientName": "WEB",
            "clientVersion": "2.20231018.01.00",
            "hl": "en",
            "gl": "US"
        }
    },
	"externalVideoId": "kNNGOrJDdO8",
	"params": "CgtrTk5HT3JKRGRPOBISQ2dOaGMzSVNBbVZ1R2dBJTNEGAEqM2VuZ2FnZW1lbnQtcGFuZWwtc2VhcmNoYWJsZS10cmFuc2NyaXB0LXNlYXJjaC1wYW5lbDABOAFAAQ%3D%3D"
}

