name: Release Obsidian plugin

on:
    push:
        tags:
            - "*"

env:
    PLUGIN_NAME: obsidian-ytranscript

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: npm

            - name: Build
              run: |
                  npm ci
                  npm run build
                  mkdir ${{ env.PLUGIN_NAME }}
                  cp main.js manifest.json styles.css ${{ env.PLUGIN_NAME }}
                  zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}

            - name: Create release
              uses: softprops/action-gh-release@v2
              with:
                  files: |
                      ${{ env.PLUGIN_NAME }}.zip
                      main.js
                      manifest.json
                      styles.css
