name: Release Obsidian plugin

on:
    push:
        tags:
            - "*"

env:
    PLUGIN_NAME: obsidian-ytranscript

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Build
              id: build
              run: |
                  npm install
                  npm run build
                  mkdir ${{ env.PLUGIN_NAME }}
                  cp main.js manifest.json styles.css ${{ env.PLUGIN_NAME }}
                  TAG_NAME=$(git tag --sort version:refname | tail -n 1)
                  zip -r ${{ env.PLUGIN_NAME }}-${TAG_NAME}.zip ${{ env.PLUGIN_NAME }}
                  ls
                  echo "tag_name=${TAG_NAME}" >> $GITHUB_OUTPUT

            - name: Create Release
              uses: softprops/action-gh-release@v2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  name: ${{ github.ref_name }}
                  draft: false
                  prerelease: false
                  files: |
                      ${{ env.PLUGIN_NAME }}-${{ steps.build.outputs.tag_name }}.zip
                      main.js
                      manifest.json
                      styles.css
